
[local]
localhost ansible_connection=local

[mongodb]
mongodb-dev.divakar88.online

[catalogue]
catalogue-dev.divakar88.online

[redis]
redis-dev.divakar88.online

[user]
user-dev.divakar88.online

[cart]
cart-dev.divakar88.online

[mysql]
mysql-dev.divakar88.online

[shipping]
shipping-dev.divakar88.online

[rabbitmq]
rabbitmq-dev.divakar88.online

[payment]
payment-dev.divakar88.online

[frontend]
frontend-dev.divakar88.online


